### ISSUE TITLE
Help needed in refactoring Readme.md

### ISSUE THREAD

**Issue by jithindasad** [GetSetCodeKerala/100-days-of-code#21]
Readme.md should be made pretty and should have a uniform structure.

**Comment by subins2000** [comment]
Different entries for the same day should be made into a list. I did this on [Day #1](https://github.com/GetSetCodeKerala/100-days-of-code/blob/d7437e90be3282d0dc9c8c9c4edd6fa38cdaac17/README.md#day-1-june-17-2018)

But please don't merge those entries into a single [preformatted textbox](https://github.com/GetSetCodeKerala/100-days-of-code#day-3-june-19-2018). It's confusing and ugly.

I have no problem with the entry being in a preformatted textbox, but then enclosing the words `Thoughts`, `Today's Progress` and `Name` with `**` doesn't make any sense.

Then there's another problem, not everyone started the challenge on the same day, so Day #0 etc. will be different for different people. This is getting messy.

We need to standardize the entry format first.

**Comment by jithindasad** [comment]
I didn't had any plans of merging entries into a preformed text box, Its exactly as you said doesn't make any sense. It was a mistake and just happened that way.

Can you make a PR on master. If its not a hustle?

**Comment by jithindasad** [comment]
issue resolved
